services:
  - type: web
    name: fedcm-idp-demo
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16.20.2
